version: "2"
services:

  app_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./allure-results:/tests/allure-results
    environment:
      BUILD_VAR_COMMAND_STRING: $env:COMMAND_STRING