version: "3"
services:
  app_test:
    build:
      context: .
      args:
        BUILD_VAR_COMMAND_STRING: ${COMMAND_STRING}
    volumes:
      - ./allure-results:/tests/allure-results
    environment:
      BUILD_VAR_COMMAND_STRING: "${COMMAND_STRING}"
    network_mode: "host"
