version: "3"
services:
  app_test:
    build: .
    volumes:
      - ./allure-results:/tests/allure-results
    environment:
      BUILD_VAR_COMMAND_STRING: ${env.COMMAND_STRING}
    network_mode: "host"
