version: "2"
services:

  app_test:
    build:
      context: .
      dockerfile: Dockerfile2
    volumes:
      - ./allure-results:/tests/allure-results
    environment:
      BUILD_VAR_COMMAND_STRING: "%COMMAND_STRING%"
