version: "2"
services:

  app_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${WORKSPACE}/allure-results:/allure-results
    entrypoint: ["python", "-m", "pytest", "runner.py", "--alluredir=allure-results"]